# Generated by Django 5.1 on 2024-08-31 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='size',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productvariants',
            options={'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(upload_to='store/Products/product_colors/'),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
