# Generated by Django 5.1 on 2024-08-31 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productsize_alter_productvariants_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='category',
        ),
    ]
