# Generated by Django 5.1 on 2024-08-31 21:31

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_productsize_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=8, max_length=20, prefix='', unique=True),
        ),
    ]
