# Generated by Django 5.1 on 2024-09-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('visible', 'Visible'), ('hiddin', 'Hiddin')], default='visible', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('hiddin', 'Hiddin')], default='visible', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Products Types',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.producttype'),
        ),
    ]
