# Generated by Django 5.1 on 2024-09-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
