# Generated by Django 5.1 on 2024-09-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Products Types'},
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
