# Generated by Django 5.1 on 2024-09-02 13:08

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_product_category_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='store/Products/product_colors/')),
            ],
        ),
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='store/categories')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('hiddin', 'Hiddin')], default='visible', max_length=20)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('size_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.sizecategory')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=12, max_length=30, prefix='pr', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail_img', models.ImageField(upload_to='store/Products/thumbnails')),
                ('featured', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('money', 'نقود'), ('points', 'نقاط')], default='money', max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('point_price', models.IntegerField(blank=True, null=True)),
                ('offer', models.BooleanField(default=False)),
                ('ready_to_sale', models.BooleanField(default=False)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/Products/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=8, max_length=20, prefix='sku', unique=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('size_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_options', to='store.sizecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='store.productitem')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='store.sizeoption')),
            ],
        ),
    ]
