# Generated by Django 5.1 on 2024-09-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productcolor_sizecategory_category_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizeoption',
            old_name='name',
            new_name='value',
        ),
        migrations.AddField(
            model_name='category',
            name='gender_cat',
            field=models.BooleanField(default=False),
        ),
    ]
