# Generated by Django 5.1 on 2024-09-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_productcolor_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='productitem',
            name='image',
            field=models.ImageField(null=True, upload_to='store/Products/product_items/'),
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
