# Generated by Django 5.1 on 2024-09-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_productitem_color_productitem_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsslider',
            options={'verbose_name': 'اعلان', 'verbose_name_plural': 'الاعلانات'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'علامة تجارية', 'verbose_name_plural': 'العلامات تجارية'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'تصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'صورة المنتج', 'verbose_name_plural': 'صور المنتج'},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'متغير المنتج', 'verbose_name_plural': 'متغيرات المنتج'},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name': 'المخزون', 'verbose_name_plural': 'المخزون'},
        ),
        migrations.AlterModelOptions(
            name='sizecategory',
            options={'verbose_name': 'فئة المقاسات', 'verbose_name_plural': 'فئات المقاسات'},
        ),
        migrations.AlterModelOptions(
            name='sizeoption',
            options={'verbose_name': 'مقاس', 'verbose_name_plural': 'المقاسات'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'هاشتاج', 'verbose_name_plural': 'هاشتاج'},
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='store.sizeoption'),
        ),
    ]
