# Generated by Django 5.1 on 2024-09-02 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_adsslider_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='store.sizeoption'),
        ),
    ]
