# Generated by Django 5.1 on 2024-09-03 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0018_alter_productvariation_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsslider',
            name='ads_for',
            field=models.CharField(choices=[('category_ads', 'Category Ads'), ('one_product_ads', 'One Product Ads'), ('special_products_ads', 'Special Products Ads')], default='special_products_ads', max_length=20),
        ),
        migrations.AddField(
            model_name='adsslider',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='adsslider',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adsslider',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adsslider',
            name='special_products',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
