# Generated by Django 5.1 on 2024-09-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_adsslider_ads_for_adsslider_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsslider',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='adsslider',
            name='object_id',
        ),
        migrations.AddField(
            model_name='adsslider',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='store.category'),
        ),
        migrations.AddField(
            model_name='adsslider',
            name='one_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='store.product'),
        ),
        migrations.AlterField(
            model_name='adsslider',
            name='ads_for',
            field=models.CharField(choices=[('category', 'Category Ads'), ('one_product', 'One Product Ads'), ('special_products', 'Special Products Ads')], default='special_products', max_length=20),
        ),
    ]
