# Generated by Django 5.1 on 2024-09-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_adsslider_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsslider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
