# Generated by Django 5.1 on 2024-09-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_adsslider_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsslider',
            name='description',
        ),
    ]
