# Generated by Django 5.1 on 2024-09-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_adsslider_description'),
    ]

    operations = [
    ]
