# Generated by Django 5.1 on 2024-09-03 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20240903_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsslider',
            name='special_products',
        ),
        migrations.CreateModel(
            name='AdsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(related_name='ads_products', to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='adsslider',
            name='special_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='store.adsproducts'),
        ),
    ]
