# Generated by Django 5.1 on 2024-09-03 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_adsslider_special_products_adsproducts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsslider',
            name='special_products',
        ),
        migrations.AddField(
            model_name='adsproducts',
            name='Ads_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adsproducts', to='store.adsslider'),
        ),
        migrations.AlterField(
            model_name='adsproducts',
            name='product',
            field=models.ManyToManyField(related_name='products', to='store.product'),
        ),
    ]
