# Generated by Django 5.1 on 2024-09-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_adsslider_special_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsslider',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
