# Generated by Django 5.1 on 2024-09-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsslider',
            name='ads_for',
            field=models.CharField(choices=[('category', 'Category Ads'), ('one_product', 'One Product Ads'), ('special_products', 'Special Products Ads'), ('just_show', 'Just For Show')], default='special_products', max_length=20),
        ),
    ]
