# Generated by Django 5.1 on 2024-09-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_adsslider_ads_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
