# Generated by Django 5.1 on 2024-09-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_product_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bonus',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
