# Generated by Django 5.1.1 on 2024-09-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='reserved',
        ),
    ]
