# Generated by Django 5.1.1 on 2024-10-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_copon_gift_giftusage_coponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='copon',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='copon',
            name='value',
            field=models.PositiveIntegerField(),
        ),
    ]
