# Generated by Django 5.1.1 on 2024-10-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_copon_sales_count_alter_copon_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copon',
            old_name='Expiration',
            new_name='expiration',
        ),
        migrations.AddField(
            model_name='copon',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
