# Generated by Django 5.1.1 on 2024-10-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_rename_expiration_copon_expiration_copon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copon',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
