# Generated by Django 5.1.1 on 2024-10-01 15:26

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_copon_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copon',
            options={'verbose_name': 'كوبون خصم', 'verbose_name_plural': 'كوبونات الخصم'},
        ),
        migrations.AlterModelOptions(
            name='coponusage',
            options={'verbose_name': 'سجلات شراء الكوبونات', 'verbose_name_plural': 'سجلات شراء الكوبونات'},
        ),
        migrations.AlterField(
            model_name='copon',
            name='code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=12, max_length=20, prefix='', unique=True),
        ),
    ]
