# Generated by Django 5.1.1 on 2024-10-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_alter_copon_options_alter_coponusage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copon',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
