# Generated by Django 5.1.1 on 2024-10-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_copon_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='copon',
            name='tags',
            field=models.ManyToManyField(to='store.tag'),
        ),
    ]
