# Generated by Django 5.1.1 on 2024-10-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_copon_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gift',
        ),
        migrations.DeleteModel(
            name='GiftUsage',
        ),
    ]
