# Generated by Django 5.1.1 on 2024-10-01 18:53

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_delete_gift_delete_giftusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=12, max_length=20, prefix='', unique=True)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='store/Cards/Gifts')),
                ('value', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(to='store.tag')),
            ],
            options={
                'verbose_name': 'كرت هدية',
                'verbose_name_plural': 'كروت هدايا',
            },
        ),
        migrations.CreateModel(
            name='GiftRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_for', models.CharField(choices=[('me', 'شراء لنفسي'), ('another', 'اهداء لصديق')], max_length=10)),
                ('recipient_name', models.CharField(max_length=100, null=True)),
                ('recipient_phone', models.CharField(max_length=15, null=True)),
                ('message', models.TextField(blank=True, max_length=300, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_recipients', to='store.gift')),
            ],
        ),
        migrations.CreateModel(
            name='GiftUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_used', models.BooleanField(default=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('gift_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجلات شراء الهدايا',
                'verbose_name_plural': 'سجلات شراء الهدايا',
            },
        ),
    ]
