# Generated by Django 5.1.1 on 2024-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_gift_giftrecipient_giftusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coponusage',
            name='buy_price',
            field=models.IntegerField(default=0),
        ),
    ]
