# Generated by Django 5.1.1 on 2024-10-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_coponusage_buy_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coponusage',
            old_name='buy_price',
            new_name='sell_price',
        ),
    ]
