# Generated by Django 5.1.1 on 2024-10-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_rename_buy_price_coponusage_sell_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='giftusage',
            name='gift_code',
        ),
        migrations.RemoveField(
            model_name='giftusage',
            name='user',
        ),
        migrations.DeleteModel(
            name='GiftRecipient',
        ),
        migrations.DeleteModel(
            name='Gift',
        ),
        migrations.DeleteModel(
            name='GiftUsage',
        ),
    ]
