# Generated by Django 5.1.1 on 2024-10-03 13:05

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_remove_gift_tags_remove_giftusage_gift_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=12, max_length=20, prefix='', unique=True)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='store/Cards/Gifts')),
                ('value', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(to='store.tag')),
            ],
            options={
                'verbose_name': 'هدية',
                'verbose_name_plural': 'هدايا',
            },
        ),
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_code', models.CharField(max_length=12, unique=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('has_used', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_items', to='store.gift')),
            ],
            options={
                'verbose_name': 'هدية مشتراة',
                'verbose_name_plural': 'هدايا مشتراة',
            },
        ),
        migrations.CreateModel(
            name='GiftRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_for', models.CharField(choices=[('me', 'شراء لنفسي'), ('another', 'إهداء لشخص آخر')], max_length=10)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField(blank=True, max_length=300, null=True)),
                ('gift_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='store.giftitem')),
            ],
            options={
                'verbose_name': 'مستلم هدية',
                'verbose_name_plural': 'مستلمو الهدايا',
            },
        ),
    ]
