# Generated by Django 5.1.1 on 2024-10-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_gift_giftitem_giftrecipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'كرت هدية', 'verbose_name_plural': 'كروت هدايا'},
        ),
        migrations.AddField(
            model_name='giftitem',
            name='sell_price',
            field=models.IntegerField(default=0),
        ),
    ]
