# Generated by Django 5.1.1 on 2024-10-03 18:06

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_alter_gift_options_giftitem_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copon',
            name='tags',
            field=models.ManyToManyField(null=True, to='store.tag'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='tags',
            field=models.ManyToManyField(null=True, to='store.tag'),
        ),
        migrations.AlterField(
            model_name='giftitem',
            name='gift_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=12, max_length=20, prefix='', unique=True),
        ),
    ]
