# Generated by Django 5.1.1 on 2024-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_alter_copon_tags_alter_gift_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftrecipient',
            name='gift_for',
            field=models.CharField(choices=[('for-me', 'شراء لنفسي'), ('for-another', 'إهداء لشخص آخر')], max_length=20),
        ),
    ]
