# Generated by Django 5.1.1 on 2024-10-03 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_alter_giftrecipient_gift_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftitem',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_items_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='copon',
            name='tags',
            field=models.ManyToManyField(blank=True, to='store.tag'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='tags',
            field=models.ManyToManyField(blank=True, to='store.tag'),
        ),
        migrations.AlterField(
            model_name='giftitem',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_items_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giftitem',
            name='sell_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
