# Generated by Django 5.1.1 on 2024-10-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_giftdealing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftdealing',
            old_name='receiver',
            new_name='receiver_phone',
        ),
        migrations.AddField(
            model_name='giftdealing',
            name='receiver_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
