# Generated by Django 5.1.1 on 2024-10-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_rename_receiver_giftdealing_receiver_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftdealing',
            name='receiver_name',
            field=models.CharField(max_length=50),
        ),
    ]
