# Generated by Django 5.1.2 on 2024-10-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_remove_orderitem_order_remove_orderitem_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales_count',
        ),
    ]
