# Generated by Django 5.1.2 on 2024-10-20 16:17

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_product_total_sales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsproducts',
            name='Ads_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adsproducts', to='store.adsslider', verbose_name='الإعلان'),
        ),
        migrations.AlterField(
            model_name='adsproducts',
            name='product',
            field=models.ManyToManyField(related_name='products', to='store.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='adsslider',
            name='ads_for',
            field=models.CharField(choices=[('category', 'تصنيف'), ('one_product', 'منتج معين'), ('special_products', ' منتجات خاصة'), ('just_show', 'منظر فقط')], default='special_products', max_length=20, verbose_name='إعلان من اجل '),
        ),
        migrations.AlterField(
            model_name='adsslider',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='store.category', verbose_name='اعلان للتصنيف ..'),
        ),
        migrations.AlterField(
            model_name='adsslider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='adsslider',
            name='img',
            field=models.ImageField(upload_to='store/Ads', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='adsslider',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='adsslider',
            name='one_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='store.product', verbose_name='اعلان للمنتج..'),
        ),
        migrations.AlterField(
            model_name='adsslider',
            name='show',
            field=models.BooleanField(default=False, verbose_name='عرض'),
        ),
        migrations.AlterField(
            model_name='adsslider',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='adsslider',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='adsslider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='مميز'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(upload_to='store/Brands', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart', verbose_name='السلة'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_variations', to='store.productvariation', verbose_name='عنصر السلة'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='مميز؟'),
        ),
        migrations.AlterField(
            model_name='category',
            name='gender_cat',
            field=models.BooleanField(default=False, verbose_name='تصنيف جنسي؟'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='store/categories', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='التصنيف الأب'),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.sizecategory', verbose_name='فئة المقاس'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('visible', 'ظاهر'), ('hiddin', 'مخفي')], default='visible', max_length=20, verbose_name='الظهور'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='products',
            field=models.ManyToManyField(to='store.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bonus',
            field=models.IntegerField(blank=True, default=20, null=True, verbose_name='المكافأة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.brand', verbose_name='البراند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='مميز؟'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر التخفيض'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='مخفض؟'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=12, max_length=30, prefix='pr', unique=True, verbose_name='المعرف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.IntegerField(default=0, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ready_to_sale',
            field=models.BooleanField(default=False, verbose_name='معروض؟'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='products', to='store.tag', verbose_name='الهاشتاج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_img',
            field=models.ImageField(upload_to='store/Products/thumbnails', verbose_name='صورة العرض'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_sales',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='إجمالي البيع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='store/Products/images', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.CharField(max_length=255, verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='image',
            field=models.ImageField(null=True, upload_to='store/Products/product_items/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', length=8, max_length=20, prefix='sku', unique=True, verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='store.productitem', verbose_name='العنصر'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='store.sizeoption', verbose_name='المقاس'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='sold',
            field=models.IntegerField(default=0, verbose_name='المباع'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='sizecategory',
            name='name',
            field=models.CharField(max_length=80, verbose_name='اسم الفئة'),
        ),
        migrations.AlterField(
            model_name='sizeoption',
            name='size_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_options', to='store.sizecategory', verbose_name='فئة المقاس'),
        ),
        migrations.AlterField(
            model_name='sizeoption',
            name='value',
            field=models.CharField(max_length=20, verbose_name='القيمة'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='الإسم'),
        ),
    ]
