# Generated by Django 5.1.2 on 2025-01-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_repository_product_repository'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name': 'مستودع', 'verbose_name_plural': 'المستودعات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.repository', verbose_name='المستودع'),
            preserve_default=False,
        ),
    ]
