# Generated by Django 5.1.6 on 2025-03-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_alter_product_new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='products',
            field=models.ManyToManyField(related_name='favourite_products', to='store.product', verbose_name='المنتج'),
        ),
    ]
