# Generated by Django 5.1.6 on 2025-03-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_alter_favourite_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='products',
            field=models.ManyToManyField(to='store.product', verbose_name='المنتج'),
        ),
    ]
