# Generated by Django 5.1.6 on 2025-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_alter_favourite_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط المنتج'),
        ),
    ]
