# Generated by Django 5.1.6 on 2025-03-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=False, verbose_name='متوفر؟'),
        ),
    ]
