# Generated by Django 5.1.6 on 2025-03-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_interested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interested',
            options={'verbose_name': 'طلب توفير منتج', 'verbose_name_plural': 'منتجات مطلوب توفيرها'},
        ),
        migrations.RemoveField(
            model_name='interested',
            name='updated_at',
        ),
    ]
