# Generated by Django 5.1.6 on 2025-04-06 17:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0072_alter_interested_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsslider',
            name='info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='الوصف'),
        ),
    ]
