# Generated by Django 5.1.6 on 2025-04-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_product_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsslider',
            name='img',
            field=models.ImageField(upload_to='store/Ads', verbose_name='[16:9]الصورة'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(upload_to='store/Brands', verbose_name='[1:1]الصورة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='store/categories', verbose_name='[1:1]الصورة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_img',
            field=models.ImageField(upload_to='store/Products/thumbnails', verbose_name='صورة العرض[1:1]'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='store/Products/images', verbose_name='[4:5]الصورة'),
        ),
    ]
