"""
Django settings for Fikra project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

with open(os.path.join(BASE_DIR, 'secret_key.txt')) as f:
    SECRET_KEY = f.read().strip()
    

ALLOWED_HOSTS = ['127.0.0.1', 'localhost','82.29.180.27', 'fikra-store.shop', 'www.fikra-store.shop']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # مهام مجدولة
    'django_celery_beat',
    
    # PWA
    'pwa',
    
    # My Custom Apps 
    'store', 
    'blog', 
    'accounts', 
    'cards',
    'orders',
    'reportes',
    'settings',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Fikra.middleware.AdminLanguageMiddleware', # كود الخاص بترجمة صفحة الادمن
]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # اجعل هذا False في بيئة الإنتاج

if DEBUG:
    INSTALLED_APPS += ['debug_toolbar', ]
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']

    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK':  lambda request: request.user.is_superuser,
    }
else:
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: False,
    }

# for toolbar Remove later
INTERNAL_IPS = [
    '127.0.0.1',
]

ROOT_URLCONF = 'Fikra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR , 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processor.social_data',
                'store.context_processor.globals',
            ],
        },
    },
]

WSGI_APPLICATION = 'Fikra.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'FikraDatabase',
        "USER": "postgres",
        "PASSWORD": "saour",
        "HOST": "localhost",
        "PORT": "",
    }
}

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://localhost:6379/1',  # استخدم قاعدة بيانات Redis رقم 1 للكاش
#     }
# }

LOGGING = {
    "version": 1,  # إصدار الإعدادات (يجب أن يكون 1)
    "disable_existing_loggers": False,  # لا تعطل الـ loggers الافتراضية
    "formatters": {  # أنماط تنسيق الرسائل
        "verbose": {
            "format": "[{levelname}] {asctime} - {name} - {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },
    "handlers": {  # وحدات التعامل مع السجلات
        "file": {  # حفظ سجلات التطبيقات في ملف
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs/debug.log"),
            "formatter": "verbose",
        },
        "db_file": {  # حفظ سجلات قاعدة البيانات في ملف
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs/db.log"),
            "formatter": "verbose",
        },
        "security_file": {  # حفظ سجلات الأمان في ملف
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs/security.log"),
            "formatter": "verbose",
        },
        "console": {  # طباعة السجلات في وحدة التحكم
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {  # تعريف الـ loggers
        "django": {  # سجل Django الأساسي
            "handlers": ["file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "django.db.backends": {  # سجل استعلامات قاعدة البيانات
            "handlers": ["db_file"],
            "level": "DEBUG",
            "propagate": False,
        },
         "django.security": {
            "handlers": ["security_file"],
            "level": "WARNING",
            "propagate": False,
        },
        #  سجلات مخصصة لكل تطبيق
        "store": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "accounts": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "cards": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "orders": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "reportes": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'accounts.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Africa/Tripoli'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'accounts:sign'  #  تخصيص صفحة تسجيل الدخول



# admin bannel customizition ========================================
JAZZMIN_SETTINGS = {
    
    # make it true when you want to edit admin theme
    "show_ui_builder": False,
    
    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "images/icons/small-logo.webp",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": 'images/admin-logo.webp',

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to Fikra store managment",

    # Copyright on the footer
    "copyright": "Fikra store",

}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
# ===================================================================

# جدولة المهام
from celery.schedules import crontab

CELERY_BROKER_URL = 'redis://localhost:6379/0'  # قاعدة بيانات Redis رقم 0 للبروكر
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # قاعدة بيانات Redis رقم 0 لحفظ النتائج

# إعدادات Celery الأخرى
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_BEAT_SCHEDULE = {
    'distribute-profits-every-7th-day-of-month': {
        'task': 'reportes.tasks.distribute_profits',
        'schedule': crontab(day_of_month='15'),  # في اليوم 15 من كل شهر
    },
    'check-copon-expire-every-day': {
        'task': 'cards.tasks.check_expire',
        'schedule': crontab(hour=0, minute=0), # كل يوم الساعة 12 صباحا
    },
}

# ===================================================================

# PWA إعدادات 
# حاليا ما عم تجي البيانات منهن عم تجي من الملف في static
PWA_APP_NAME = "FIKRA"
PWA_APP_DESCRIPTION = "Fikra Clothing Store"
PWA_APP_THEME_COLOR = "#292929"
PWA_APP_BACKGROUND_COLOR = "#232323"
PWA_APP_DISPLAY = "standalone"
PWA_APP_SCOPE = "/"
PWA_APP_START_URL = "/"
PWA_SERVICE_WORKER_PATH = None
PWA_APP_ICONS = [
    {
        "src": "/static/images/icons/small-logo.webp",
        "sizes": "192x192"
    }
]
PWA_APP_SCREENSHOTS = [
    {
        "src": "/static/images/screenshots/screenshot1.jpg",
        "sizes": "1080x1920",
        "type": "image/jpeg", 
        "form_factor": "wide"
    },
    {
        "src": "/static/images/screenshots/screenshot2.jpg",
        "sizes": '720x1280',
        "type": "image/jpg",  
        "form_factor": "narrow"
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        "src": "/static/images/screenshots/splach.jpg",
        "sizes": "720x1280",
        "type": "image/jpg"
    }
]
# ===================================================================
# الية ارسال رسائل التحقق 

TWILIO_ACCOUNT_SID = "AC200e05d17d57d421bb92749b61f6b066"
TWILIO_AUTH_TOKEN = "8008619ef764a8fe2642dcdb93dd4f51"
TWILIO_TEMPLATE_SID = "HX733e19494218efb70a37264db95cb199"
TWILIO_WHATSAPP_NUMBER = "+218923898325" 


#  HTTPS SETTINGS
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True

# # HSTS SETTINGS 
# SECURE_HSTS_SECONDS = 31536000 # 1 YEAR
# SECURE_HSTS_PRELOAD = True
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True