# Generated by Django 5.1.1 on 2024-09-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_message_inbox_userpoints_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_points',
        ),
        migrations.AlterModelOptions(
            name='inbox',
            options={'verbose_name': 'البريد', 'verbose_name_plural': 'البريد'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'رسالة', 'verbose_name_plural': 'رسائل'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'مستخدمين'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'بروفايل', 'verbose_name_plural': 'بروفايل'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserPoints',
        ),
    ]
