# Generated by Django 5.1.2 on 2024-10-20 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_created_at_userprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='messages',
            field=models.ManyToManyField(related_name='inboxes', to='accounts.message', verbose_name='الرسائل'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='مقروئة؟'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=250, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='pointsusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='pointsusage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='التفاصيل'),
        ),
        migrations.AlterField(
            model_name='pointsusage',
            name='new_points',
            field=models.IntegerField(verbose_name='الرصيد الجديد'),
        ),
        migrations.AlterField(
            model_name='pointsusage',
            name='old_points',
            field=models.IntegerField(verbose_name='الرصيد القديم'),
        ),
        migrations.AlterField(
            model_name='pointsusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='pointsusage',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='البروفايل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inbox',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.inbox', verbose_name='البريد'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='الرصيد'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
