# Generated by Django 5.1.2 on 2025-01-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_inbox_messages_alter_inbox_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_to_all',
            field=models.BooleanField(default=False, verbose_name='مرسلة للجميع؟'),
        ),
    ]
