# Generated by Django 5.1.5 on 2025-02-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_otpverification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
