# Generated by Django 5.1.5 on 2025-02-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_otpverification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='user',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
