# Generated by Django 5.1.5 on 2025-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_otpverification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
