# Generated by Django 5.1.5 on 2025-02-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsusage',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile', verbose_name='البروفايل'),
        ),
    ]
