# Generated by Django 5.1.5 on 2025-02-26 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_pointsusage_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsusage',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='البروفايل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_city', to='accounts.city', verbose_name='المدينة'),
        ),
    ]
