# Generated by Django 5.1.6 on 2025-04-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_banned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=20, verbose_name='الرصيد'),
        ),
    ]
