# Generated by Django 5.1 on 2024-09-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'صفحة مدونة', 'verbose_name_plural': 'صفحات المدونة '},
        ),
        migrations.AlterModelOptions(
            name='questionpage',
            options={'verbose_name': 'صفحة الاسئلة ', 'verbose_name_plural': 'صفحة الاسئلة '},
        ),
        migrations.AddField(
            model_name='blogpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
