# Generated by Django 5.1 on 2024-09-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpage_options_alter_questionpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
