# Generated by Django 5.1 on 2024-09-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questioncontent',
            old_name='question_page',
            new_name='questions_page',
        ),
    ]
