# Generated by Django 5.1.1 on 2024-10-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_question_page_questioncontent_questions_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncontent',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
