# Generated by Django 5.1.1 on 2024-10-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_questioncontent_slug_alter_blogpage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncontent',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
