# Generated by Django 5.1.2 on 2024-10-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_questioncontent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/pages', verbose_name='الخلفية'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='blog_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blogpage', verbose_name='الصفحة'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='order',
            field=models.IntegerField(default=100, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='questioncontent',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='questioncontent',
            name='order',
            field=models.IntegerField(default=100, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='questioncontent',
            name='questions_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='blog.questionpage', verbose_name='الصفحة'),
        ),
        migrations.AlterField(
            model_name='questioncontent',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='questioncontent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='questionpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/questions/', verbose_name='الخلفية'),
        ),
        migrations.AlterField(
            model_name='questionpage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='العنوان'),
        ),
    ]
