# Generated by Django 5.1.6 on 2025-04-06 17:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpage_image_alter_blogpage_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='questioncontent',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='المحتوى'),
        ),
    ]
