# Generated by Django 5.1.2 on 2024-11-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_return_days', models.IntegerField(verbose_name='اقصى مدة استرجاع')),
                ('max_replace_days', models.IntegerField(verbose_name='اقصى مدة استبدال')),
                ('partners_percentage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='نسبة الشركاء')),
            ],
            options={
                'verbose_name': 'الإعدادات',
                'verbose_name_plural': 'الإعدادات',
            },
        ),
    ]
