# Generated by Django 5.1.2 on 2024-11-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='max_replace_days',
            field=models.IntegerField(default=3, verbose_name='اقصى مدة استبدال'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='max_return_days',
            field=models.IntegerField(default=3, verbose_name='اقصى مدة استرجاع'),
        ),
    ]
