# Generated by Django 5.1.2 on 2025-01-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_max_replace_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='free_delivery',
            field=models.BooleanField(default=False, verbose_name='توصيل مجاني؟'),
        ),
    ]
