# Generated by Django 5.1.2 on 2025-01-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_settings_free_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='partners_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='نسبة الشركاء'),
        ),
    ]
