# Generated by Django 5.1.2 on 2025-01-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_settings_partners_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('instagram', models.URLField(blank=True, verbose_name='انستا')),
                ('whatsapp', models.IntegerField(blank=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ايميل')),
            ],
            options={
                'verbose_name': 'حسابات الموقع',
                'verbose_name_plural': 'حسابات الموقع',
            },
        ),
    ]
