# Generated by Django 5.1.2 on 2025-01-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='phone_number1',
            field=models.IntegerField(null=True, verbose_name='رقم الهاتف الاساسي'),
        ),
        migrations.AddField(
            model_name='social',
            name='phone_number2',
            field=models.IntegerField(null=True, verbose_name='رقم الهاتف الثانوي'),
        ),
        migrations.AlterField(
            model_name='social',
            name='whatsapp',
            field=models.IntegerField(blank=True, verbose_name='رقم الواتساب'),
        ),
    ]
