# Generated by Django 5.1.2 on 2025-01-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_social_phone_number1_social_phone_number2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='phone_number1',
            field=models.CharField(max_length=20, null=True, verbose_name='رقم الهاتف الاساسي'),
        ),
        migrations.AlterField(
            model_name='social',
            name='phone_number2',
            field=models.CharField(max_length=20, null=True, verbose_name='رقم الهاتف الثانوي'),
        ),
        migrations.AlterField(
            model_name='social',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الواتساب'),
        ),
    ]
