# Generated by Django 5.1.5 on 2025-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_social_phone_number1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='replace_possibility',
            field=models.BooleanField(default=True, verbose_name='إمكانية الاستبدال'),
        ),
        migrations.AddField(
            model_name='settings',
            name='return_possibility',
            field=models.BooleanField(default=True, verbose_name='إمكانية الإرجاع'),
        ),
    ]
