# Generated by Django 5.1.5 on 2025-02-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_settings_replace_possibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='expected_days',
            field=models.IntegerField(default=7, verbose_name='عدد الأيام المتوقع لوصول الطلب'),
        ),
    ]
