# Generated by Django 5.1.5 on 2025-02-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_settings_expected_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='expected_days',
            field=models.IntegerField(default=7, verbose_name=' الأيام المتوقعة لوصول الطلب'),
        ),
    ]
