# Generated by Django 5.1.6 on 2025-04-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_alter_social_tiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='send_otp_by_twillow',
            field=models.BooleanField(default=False, verbose_name='ارسال رسائل التحقق'),
        ),
    ]
