# Generated by Django 5.1.6 on 2025-04-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_settings_send_otp_by_twillow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='send_otp_by_twillow',
            new_name='send_otp_by_twilio',
        ),
    ]
