# Generated by Django 5.1.2 on 2024-10-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_price', models.IntegerField(verbose_name='سعر الكيس')),
                ('packaging_paper_price', models.IntegerField()),
                ('thanks_card_price', models.IntegerField()),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'تغليف',
                'verbose_name_plural': 'ميزانية التغليف',
            },
        ),
    ]
