# Generated by Django 5.1.2 on 2024-10-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packaging',
            name='bag_price',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='سعر الكيس'),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='packaging_paper_price',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='سعر ورق التغليف'),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='thanks_card_price',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='سعر بطاقة الشكر'),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='الإجمالي'),
        ),
    ]
