# Generated by Django 5.1.2 on 2024-10-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0006_monthlytotal_alter_packaging_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': 'دخل', 'verbose_name_plural': 'مدخول'},
        ),
        migrations.AddField(
            model_name='monthlytotal',
            name='additional_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي الدخل الإضافي'),
        ),
    ]
