# Generated by Django 5.1.2 on 2024-10-20 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_alter_cost_options_monthlytotal_additional_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': 'تكلفة', 'verbose_name_plural': 'التكاليف'},
        ),
        migrations.AddField(
            model_name='monthlytotal',
            name='sales_number',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='AdditionalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='الاسم')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='reportes.monthlytotal', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'دخل',
                'verbose_name_plural': 'مدخول',
            },
        ),
    ]
