# Generated by Django 5.1.2 on 2024-10-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_alter_cost_options_monthlytotal_sales_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalincome',
            options={'verbose_name': 'دخل', 'verbose_name_plural': 'المدخلات'},
        ),
        migrations.AlterModelOptions(
            name='packformonth',
            options={'verbose_name_plural': 'تكلفة التغليف'},
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='additional_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي الإضافات'),
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='sales_number',
            field=models.IntegerField(null=True, verbose_name='عدد المبيعات'),
        ),
    ]
