# Generated by Django 5.1.2 on 2024-10-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_alter_additionalincome_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlytotal',
            options={'verbose_name': 'المجموع الشهري', 'verbose_name_plural': 'الإحصائيات الشهرية'},
        ),
    ]
