# Generated by Django 5.1.2 on 2024-10-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0010_alter_monthlytotal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
            ],
            options={
                'verbose_name': 'مستثمر',
                'verbose_name_plural': 'المستثمرين',
            },
        ),
        migrations.CreateModel(
            name='InvestmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الحصة')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المتبقي')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المسترد')),
                ('completed', models.BooleanField(default=False, verbose_name='فعالة؟')),
            ],
            options={
                'verbose_name': 'مجموعة استثمارية',
                'verbose_name_plural': 'المجموعات الاستثمارية ',
            },
        ),
        migrations.AddField(
            model_name='partners',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='share_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='النسبة'),
        ),
        migrations.CreateModel(
            name='InvestmentGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة المبلغ الاستثماري')),
                ('investment_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='النسبة')),
                ('profit_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='الربح')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='reportes.investmentgroup', verbose_name='المجموعة')),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='reportes.investigator', verbose_name='المستثمر')),
            ],
            options={
                'verbose_name': 'عضو المجموعة الاستثمارية',
                'verbose_name_plural': 'اعضاء المجموعات الاستثمارية',
            },
        ),
        migrations.CreateModel(
            name='PartnersProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الربح')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_profit', to='reportes.monthlytotal', verbose_name='الشهر')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profit', to='reportes.partners', verbose_name='الشريك')),
            ],
            options={
                'verbose_name': 'ربح الشريك الشهري',
                'verbose_name_plural': 'ارباح الشركاء الشهرية',
            },
        ),
    ]
