# Generated by Django 5.1.2 on 2024-10-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0011_investigator_investmentgroup_partners_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
