# Generated by Django 5.1.2 on 2024-10-21 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0012_alter_partners_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnersprofit',
            options={'verbose_name': 'الربح', 'verbose_name_plural': 'الأرباح'},
        ),
        migrations.AddField(
            model_name='investmentgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
    ]
