# Generated by Django 5.1.2 on 2024-10-21 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0013_alter_partnersprofit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنضمام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='investmentgroupmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنضمام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentgroupmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='partners',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنضمام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AddField(
            model_name='partnersprofit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnersprofit',
            name='received',
            field=models.BooleanField(default=False, verbose_name='تم التسليم؟'),
        ),
        migrations.AddField(
            model_name='partnersprofit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='partnersprofit',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_monthly_profits', to='reportes.monthlytotal', verbose_name='الشهر'),
        ),
        migrations.AlterField(
            model_name='partnersprofit',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profits', to='reportes.partners', verbose_name='الشريك'),
        ),
        migrations.CreateModel(
            name='InvestigatorProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الربح')),
                ('received', models.BooleanField(default=False, verbose_name='تم التسليم؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_profit', to='reportes.investmentgroup', verbose_name='المجموعة')),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigator_profits', to='reportes.investigator', verbose_name='المستثمر')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigator_monthly_profits', to='reportes.monthlytotal', verbose_name='الشهر')),
            ],
            options={
                'verbose_name': 'ربح المستثمر',
                'verbose_name_plural': 'ارباح المستثمرين',
            },
        ),
    ]
