# Generated by Django 5.1.2 on 2024-10-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0014_investigator_created_at_investigator_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigatorprofit',
            name='group',
        ),
    ]
