# Generated by Django 5.1.2 on 2024-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0015_remove_investigatorprofit_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentgroupmember',
            options={'verbose_name': 'عضو', 'verbose_name_plural': 'الأعضاء'},
        ),
        migrations.AlterField(
            model_name='investmentgroupmember',
            name='investment_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' المبلغ الاستثماري'),
        ),
        migrations.AlterField(
            model_name='partnersprofit',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='الربح'),
        ),
    ]
