# Generated by Django 5.1.2 on 2024-10-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0016_alter_investmentgroupmember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentgroup',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='جاهزة؟'),
        ),
        migrations.AlterField(
            model_name='investmentgroup',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='مكتملة؟'),
        ),
    ]
