# Generated by Django 5.1.2 on 2024-10-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0018_alter_investmentgroup_refund_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyInvestmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_percentage', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='النسبة من الاجمالي')),
                ('goods_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='من البضاعة')),
                ('profit_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='من الربح')),
                ('investment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_totals', to='reportes.investmentgroup', verbose_name='مجموعة استثمارية')),
                ('monthly_total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_groups', to='reportes.monthlytotal', verbose_name='إحصائية شهرية')),
            ],
            options={
                'verbose_name': 'مجموعة استثمارية شهرية',
                'verbose_name_plural': 'المجموعات الاستثمارية الشهرية',
            },
        ),
    ]
