# Generated by Django 5.1.2 on 2024-10-21 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0019_monthlyinvestmentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyinvestmentgroup',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name=' الإجمالي'),
        ),
        migrations.AlterField(
            model_name='monthlyinvestmentgroup',
            name='goods_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ المسترد'),
        ),
        migrations.AlterField(
            model_name='monthlyinvestmentgroup',
            name='investment_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_totals', to='reportes.investmentgroup', verbose_name='المجموعة'),
        ),
        migrations.AlterField(
            model_name='monthlyinvestmentgroup',
            name='monthly_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='النسبة الشهرية'),
        ),
        migrations.AlterField(
            model_name='monthlyinvestmentgroup',
            name='profit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name=' الربح'),
        ),
    ]
