# Generated by Django 5.1.2 on 2024-10-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0020_monthlyinvestmentgroup_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentgroup',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='العوائد'),
        ),
        migrations.AlterField(
            model_name='investmentgroupmember',
            name='investment_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' المبلغ المستثمر'),
        ),
        migrations.AlterField(
            model_name='investmentgroupmember',
            name='profit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='العائد'),
        ),
        migrations.AlterField(
            model_name='monthlyinvestmentgroup',
            name='goods_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='من البضاعة'),
        ),
        migrations.AlterField(
            model_name='monthlyinvestmentgroup',
            name='profit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='من الربح'),
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='additional_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name=' الإضافات'),
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='sales_number',
            field=models.IntegerField(null=True, verbose_name='المنتجات المباعة'),
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='total_costs',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name=' التكاليف'),
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='total_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name=' الدخل'),
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي الربح'),
        ),
    ]
