# Generated by Django 5.1.2 on 2024-10-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0021_alter_investmentgroup_refund_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigatorprofit',
            name='from_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigator_group_profits', to='reportes.investmentgroup', verbose_name='من المجموعة'),
        ),
    ]
