# Generated by Django 5.1.2 on 2024-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0022_investigatorprofit_from_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytotal',
            name='additional_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=' الإضافات'),
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='goods_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر البضاعة'),
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='sales_number',
            field=models.IntegerField(default=0, verbose_name='المنتجات المباعة'),
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='total_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=' التكاليف'),
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=' الدخل'),
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='total_packaging',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='إجمالي التغليف'),
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='إجمالي الربح'),
        ),
    ]
