# Generated by Django 5.1.2 on 2024-11-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0025_alter_monthlytotal_additional_income_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalincome',
            options={'verbose_name': 'دخل', 'verbose_name_plural': 'الإضافات'},
        ),
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': 'مصروف', 'verbose_name_plural': 'المصاريف'},
        ),
        migrations.AlterField(
            model_name='monthlytotal',
            name='total_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name=' المصاريف'),
        ),
    ]
