# Generated by Django 5.1.2 on 2024-11-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0026_alter_additionalincome_options_alter_cost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlytotal',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'المجموع الشهري', 'verbose_name_plural': 'الإحصائيات الشهرية'},
        ),
    ]
