# Generated by Django 5.1.6 on 2025-04-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0027_alter_monthlytotal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalincome',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة'),
        ),
    ]
