# Generated by Django 5.1.6 on 2025-04-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0028_alter_additionalincome_value_alter_cost_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentgroup',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='العوائد'),
        ),
        migrations.AlterField(
            model_name='investmentgroup',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المبلغ المتبقي'),
        ),
        migrations.AlterField(
            model_name='investmentgroup',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='الحصة'),
        ),
    ]
