# Generated by Django 5.1.6 on 2025-04-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0029_alter_investmentgroup_refund_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_percentage', models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='النسبة الشهرية')),
                ('goods_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='من البضاعة')),
                ('profit_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='من الربح')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name=' الإجمالي')),
                ('monthly_total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_profit', to='reportes.monthlytotal', verbose_name='إحصائية شهرية')),
            ],
            options={
                'verbose_name': 'ربح المتجر الشهري',
                'verbose_name_plural': 'ارباح المتجر الشهرية',
            },
        ),
    ]
