# Generated by Django 5.1.6 on 2025-04-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0030_storeprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytotal',
            name='contributing_groups',
            field=models.ManyToManyField(blank=True, to='reportes.investmentgroup', verbose_name='المجموعات المساهمة'),
        ),
    ]
