# Generated by Django 5.1.1 on 2024-10-04 16:35

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0058_remove_coponusage_copon_code_remove_coponusage_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Copon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=12, max_length=20, prefix='', unique=True)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='store/Cards/Copons')),
                ('value', models.PositiveIntegerField()),
                ('min_bill_price', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration', models.DateField()),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, to='store.tag')),
            ],
            options={
                'verbose_name': 'كوبون خصم',
                'verbose_name_plural': 'كوبونات الخصم',
            },
        ),
        migrations.CreateModel(
            name='CoponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.IntegerField(default=0)),
                ('has_used', models.BooleanField(default=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('copon_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.copon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجلات شراء الكوبونات',
                'verbose_name_plural': 'سجلات شراء الكوبونات',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=12, max_length=20, prefix='', unique=True)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='store/Cards/Gifts')),
                ('value', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, to='store.tag')),
            ],
            options={
                'verbose_name': 'كرت هدية',
                'verbose_name_plural': 'كروت هدايا',
            },
        ),
        migrations.CreateModel(
            name='GiftDealing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('is_dealt', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ايصال هدية',
                'verbose_name_plural': 'ايصال هدايا',
            },
        ),
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_code', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=12, max_length=20, prefix='', unique=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('sell_price', models.PositiveIntegerField(default=0)),
                ('has_used', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_items_buyer', to=settings.AUTH_USER_MODEL)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_items', to='cards.gift')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_items_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'هدية مشتراة',
                'verbose_name_plural': 'هدايا مشتراة',
            },
        ),
        migrations.CreateModel(
            name='GiftRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_for', models.CharField(choices=[('for-me', 'شراء لنفسي'), ('for-another', 'إهداء لشخص آخر')], max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField(blank=True, max_length=300, null=True)),
                ('gift_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='cards.giftitem')),
            ],
            options={
                'verbose_name': 'مستلم هدية',
                'verbose_name_plural': 'مستلمو الهدايا',
            },
        ),
    ]
