# Generated by Django 5.1.1 on 2024-10-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftitem',
            options={'verbose_name': 'سجل شراء هدية', 'verbose_name_plural': ' سجلات شراء الهدايا'},
        ),
    ]
