# Generated by Django 5.1.1 on 2024-10-05 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_giftitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copon',
            name='expiration',
        ),
        migrations.AddField(
            model_name='copon',
            name='expiration_days',
            field=models.IntegerField(default=365),
        ),
        migrations.AddField(
            model_name='coponusage',
            name='expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coponusage',
            name='copon_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copon_usage', to='cards.copon'),
        ),
    ]
