# Generated by Django 5.1.1 on 2024-10-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_copon_expiration_copon_expiration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coponusage',
            name='expire',
            field=models.DateTimeField(),
        ),
    ]
