# Generated by Django 5.1.1 on 2024-10-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_coponusage_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coponusage',
            name='expire',
            field=models.DateField(),
        ),
    ]
