# Generated by Django 5.1.1 on 2024-10-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_coponusage_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdealing',
            name='sell_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giftdealing',
            name='sell_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giftitem',
            name='sell_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
