# Generated by Django 5.1.1 on 2024-10-07 09:38

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_giftrecipient_gift_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=12, max_length=20, prefix='', unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('value', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'كود استلام هدية',
                'verbose_name_plural': 'اكواد استلام هدايا',
            },
        ),
        migrations.RemoveField(
            model_name='giftitem',
            name='gift_code',
        ),
        migrations.AddField(
            model_name='giftdealing',
            name='receive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.receivegift'),
        ),
    ]
