# Generated by Django 5.1.1 on 2024-10-07 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_receivegift_remove_giftitem_gift_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivegift',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivegift',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
