# Generated by Django 5.1.1 on 2024-10-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_receivegift_created_at_receivegift_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivegift',
            name='gift',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='receive_gift', to='cards.gift'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giftdealing',
            name='receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.receivegift'),
        ),
    ]
