# Generated by Django 5.1.1 on 2024-10-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_receivegift_gift_alter_giftdealing_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivegift',
            name='gift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_gift', to='cards.gift'),
        ),
    ]
