# Generated by Django 5.1.1 on 2024-10-07 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_alter_receivegift_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftdealing',
            name='receive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.receivegift'),
        ),
    ]
