# Generated by Django 5.1.1 on 2024-10-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_alter_giftdealing_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftitem',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='giftdealing',
            name='receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.receivegift'),
        ),
        migrations.AlterField(
            model_name='receivegift',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_gift', to='cards.gift'),
        ),
    ]
