# Generated by Django 5.1.1 on 2024-10-07 15:33

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_giftitem_is_seen_alter_giftdealing_receive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftrecipient',
            name='gift_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='cards.giftitem'),
        ),
        migrations.AlterField(
            model_name='receivegift',
            name='code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=12, max_length=20, prefix='', unique=True),
        ),
    ]
