# Generated by Django 5.1.2 on 2024-10-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_alter_giftrecipient_gift_item_alter_receivegift_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftrecipient',
            name='gift_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_recipients', to='cards.giftitem'),
        ),
    ]
