# Generated by Django 5.1.2 on 2024-10-17 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_alter_giftrecipient_gift_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdealing',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_dealing_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftdealing',
            name='message',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='giftdealing',
            name='receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealing', to='cards.receivegift'),
        ),
    ]
