# Generated by Django 5.1.2 on 2024-10-17 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_alter_giftdealing_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftdealing',
            name='receive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealing', to='cards.receivegift'),
        ),
    ]
