# Generated by Django 5.1.2 on 2024-10-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_alter_giftdealing_receive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftdealing',
            name='receive',
        ),
    ]
