# Generated by Django 5.1.5 on 2025-02-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0026_alter_copon_code_alter_copon_expiration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coponusage',
            name='copon_code',
        ),
        migrations.RemoveField(
            model_name='coponusage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='giftitem',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='receivegift',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='giftdealing',
            name='receive',
        ),
        migrations.RemoveField(
            model_name='giftdealing',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='giftitem',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='giftitem',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='giftrecipient',
            name='gift_item',
        ),
        migrations.DeleteModel(
            name='Copon',
        ),
        migrations.DeleteModel(
            name='CoponUsage',
        ),
        migrations.DeleteModel(
            name='Gift',
        ),
        migrations.DeleteModel(
            name='ReceiveGift',
        ),
        migrations.DeleteModel(
            name='GiftDealing',
        ),
        migrations.DeleteModel(
            name='GiftItem',
        ),
        migrations.DeleteModel(
            name='GiftRecipient',
        ),
    ]
