# Generated by Django 5.1.5 on 2025-02-20 09:03

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0027_remove_coponusage_copon_code_remove_coponusage_user_and_more'),
        ('store', '0065_alter_repository_options_alter_product_repository'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Copon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=12, max_length=20, prefix='', unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=30, verbose_name='الاسم')),
                ('img', models.ImageField(upload_to='store/Cards/Copons', verbose_name='الصورة')),
                ('value', models.PositiveIntegerField(verbose_name='القيمة')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل؟')),
                ('expiration_days', models.IntegerField(default=365, verbose_name='يفسد بعد')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='عدد المبيعات')),
                ('tags', models.ManyToManyField(blank=True, to='store.tag', verbose_name='الهاشتاج')),
            ],
            options={
                'verbose_name': 'كوبون خصم',
                'verbose_name_plural': 'كوبونات الخصم',
            },
        ),
        migrations.CreateModel(
            name='CoponItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.IntegerField(default=0, verbose_name='السعر بالنقاط')),
                ('has_used', models.BooleanField(default=False, verbose_name='حالة الاستعمال')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الشراء')),
                ('expire', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('receive_from_code', models.BooleanField(default=False, verbose_name='هل تم الحصول عليه من كود؟')),
                ('copon_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copon_usage', to='cards.copon', verbose_name='الكود')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المشتري')),
            ],
            options={
                'verbose_name': 'سجلات شراء الكوبونات',
                'verbose_name_plural': 'سجلات شراء الكوبونات',
            },
        ),
        migrations.CreateModel(
            name='ReceiveCopon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=12, max_length=20, prefix='', unique=True, verbose_name='الكود')),
                ('is_used', models.BooleanField(default=False, verbose_name='مستعمل؟')),
                ('value', models.PositiveIntegerField(verbose_name='القيمة')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('copon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_copon', to='cards.copon', verbose_name='الكوبون')),
            ],
            options={
                'verbose_name': 'كود استلام كوبون',
                'verbose_name_plural': 'اكواد استلام كوبونات',
            },
        ),
    ]
