# Generated by Django 5.1.5 on 2025-02-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0028_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivecopon',
            name='value',
        ),
    ]
