# Generated by Django 5.1.5 on 2025-02-20 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0029_remove_receivecopon_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receivecopon',
            name='used_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='استعمل بواسطة'),
        ),
        migrations.AlterField(
            model_name='coponitem',
            name='copon_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copon_usage', to='cards.copon', verbose_name='الكوبون'),
        ),
        migrations.AlterField(
            model_name='coponitem',
            name='receive_from_code',
            field=models.BooleanField(default=False, verbose_name='استلم من كود؟'),
        ),
        migrations.AlterField(
            model_name='coponitem',
            name='sell_price',
            field=models.IntegerField(default=0, verbose_name='سعر البيع بالنقاط'),
        ),
    ]
