# Generated by Django 5.1.6 on 2025-04-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0030_receivecopon_used_by_alter_coponitem_copon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivecopon',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة'),
        ),
    ]
