# Generated by Django 5.1.2 on 2024-10-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DliveryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'سعر التوصيل ',
                'verbose_name_plural': 'سعر التوصيل',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'طلب ', 'verbose_name_plural': 'طلبات'},
        ),
    ]
