# Generated by Django 5.1.2 on 2024-10-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dliveryprice_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'طلب ', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'جاري المعالجة'), ('checking', 'جاري التجهيز'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('canceled', 'تم الإلغاء')], default='pending', max_length=20),
        ),
    ]
