# Generated by Django 5.1.2 on 2024-10-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='old_total',
            field=models.IntegerField(default=0),
        ),
    ]
