# Generated by Django 5.1.2 on 2024-10-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_old_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='old_total',
            field=models.IntegerField(),
        ),
    ]
