# Generated by Django 5.1.2 on 2024-10-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_old_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
