# Generated by Django 5.1.2 on 2024-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='serial_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
