# Generated by Django 5.1.2 on 2024-10-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverey_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
