# Generated by Django 5.1.2 on 2024-10-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_deliverey_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
