# Generated by Django 5.1.2 on 2024-10-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='returned',
        ),
    ]
