# Generated by Django 5.1.2 on 2024-10-19 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_orderitem_returned'),
        ('store', '0062_product_total_sales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'جاري المعالجة'), ('checking', 'جاري التجهيز'), ('shipped', 'جاري الشحن'), ('delivered', 'تم التسليم'), ('canceled', 'تم الإلغاء')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderDealing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_qty', models.IntegerField(blank=True, null=True)),
                ('price_difference', models.IntegerField(blank=True, null=True)),
                ('is_dealt', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('return', 'إرجاع'), ('replace', 'إستبدال')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_deals', to='store.productvariation')),
                ('old_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_deals', to='store.productvariation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عملية تعديل الطلب',
                'verbose_name_plural': 'عمليات تعديل الطلب',
            },
        ),
    ]
