# Generated by Django 5.1.2 on 2024-10-19 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_status_orderdealing'),
        ('store', '0062_product_total_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdealing',
            old_name='new_qty',
            new_name='total_price_difference',
        ),
        migrations.RemoveField(
            model_name='orderdealing',
            name='new_item',
        ),
        migrations.RemoveField(
            model_name='orderdealing',
            name='old_item',
        ),
        migrations.RemoveField(
            model_name='orderdealing',
            name='price_difference',
        ),
        migrations.CreateModel(
            name='OrderDealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_qty', models.IntegerField(blank=True, null=True)),
                ('price_difference', models.IntegerField(blank=True, null=True)),
                ('new_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_deals', to='store.productvariation')),
                ('old_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_deals', to='orders.orderitem')),
                ('order_dealing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_items', to='orders.orderdealing')),
            ],
            options={
                'verbose_name': 'عنصر تعديل الطلب',
                'verbose_name_plural': 'عناصر تعديل الطلب',
            },
        ),
    ]
