# Generated by Django 5.1.2 on 2024-10-19 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_rename_new_qty_orderdealing_total_price_difference_and_more'),
        ('store', '0062_product_total_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdealing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderdealing',
            name='user',
        ),
        migrations.AlterField(
            model_name='orderdealing',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderdealing',
            name='total_price_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DealingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_qty', models.IntegerField(blank=True, null=True)),
                ('price_difference', models.IntegerField(blank=True, null=True)),
                ('is_dealt', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('return', 'إرجاع'), ('replace', 'إستبدال')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_deals', to='store.productvariation')),
                ('old_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_deals', to='store.productvariation')),
                ('order_dealing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='orders.orderdealing')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderDealItem',
        ),
    ]
