# Generated by Django 5.1.2 on 2024-10-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_dealingitem_is_seen_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealingitem',
            name='is_seen_by_admin',
        ),
    ]
