# Generated by Django 5.1.2 on 2024-10-20 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_dealingitem_is_seen_by_admin'),
        ('store', '0063_alter_adsproducts_ads_name_alter_adsproducts_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealingitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='dealingitem',
            name='is_dealt',
            field=models.BooleanField(default=False, verbose_name='المعالجة'),
        ),
        migrations.AlterField(
            model_name='dealingitem',
            name='new_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_deals', to='store.productvariation', verbose_name='المنتج الجديد'),
        ),
        migrations.AlterField(
            model_name='dealingitem',
            name='new_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='الكمية الجديدة'),
        ),
        migrations.AlterField(
            model_name='dealingitem',
            name='old_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_deals', to='store.productvariation', verbose_name='المنتج القديم'),
        ),
        migrations.AlterField(
            model_name='dealingitem',
            name='order_dealing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='orders.orderdealing', verbose_name='طلب المعالجة'),
        ),
        migrations.AlterField(
            model_name='dealingitem',
            name='price_difference',
            field=models.IntegerField(blank=True, null=True, verbose_name='فرق السعر'),
        ),
        migrations.AlterField(
            model_name='dealingitem',
            name='status',
            field=models.CharField(blank=True, choices=[('return', 'إرجاع'), ('replace', 'إستبدال')], max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='dealingitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='dliveryprice',
            name='price',
            field=models.IntegerField(default=0, verbose_name='سعر التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliverey_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.IntegerField(default=0, verbose_name='قيمة الخصم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dlivery_price',
            field=models.IntegerField(default=0, verbose_name='سعر التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='old_total',
            field=models.IntegerField(verbose_name='الإجمالي القديم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='serial_number',
            field=models.IntegerField(unique=True, verbose_name='الرقم التسلسلي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'جاري المعالجة'), ('checking', 'جاري التجهيز'), ('shipped', 'جاري الشحن'), ('delivered', 'تم التسليم'), ('canceled', 'تم الإلغاء')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_points',
            field=models.PositiveIntegerField(null=True, verbose_name='المكافأة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='with_message',
            field=models.BooleanField(default=False, verbose_name='مع رسالة؟'),
        ),
        migrations.AlterField(
            model_name='orderdealing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='orderdealing',
            name='is_dealt',
            field=models.BooleanField(default=False, verbose_name='الاستجابة'),
        ),
        migrations.AlterField(
            model_name='orderdealing',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='orderdealing',
            name='total_price_difference',
            field=models.IntegerField(default=0, null=True, verbose_name='فرق السعر'),
        ),
        migrations.AlterField(
            model_name='orderdealing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.productvariation', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='points',
            field=models.IntegerField(null=True, verbose_name='المكافأة'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='الكمية'),
        ),
    ]
