# Generated by Django 5.1.2 on 2024-11-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_dealingitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('confirmed', 'مؤكد'), ('replaced', 'مُستبدل'), ('returned', 'مُرجع')], default='confirmed', max_length=15),
        ),
    ]
