# Generated by Django 5.1.2 on 2024-11-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('confirmed', 'مؤكد'), ('replaced', 'مُستبدل')], default='confirmed', max_length=15),
        ),
    ]
