# Generated by Django 5.1.2 on 2024-11-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealingitem',
            name='old_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='الكمية القديمة'),
        ),
    ]
