# Generated by Django 5.1.2 on 2024-11-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_dealingitem_old_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdealing',
            name='total_price_difference',
        ),
    ]
