# Generated by Django 5.1.2 on 2024-11-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_orderdealing_total_price_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdealing',
            name='remaining',
            field=models.IntegerField(null=True, verbose_name='المتبقي'),
        ),
    ]
