# Generated by Django 5.1.2 on 2024-11-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_orderdealing_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdealing',
            name='remaining',
            field=models.IntegerField(default=0, verbose_name='المتبقي'),
        ),
    ]
