# Generated by Django 5.1.2 on 2025-01-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_orderdealing_remaining'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DliveryPrice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dlivery_price',
        ),
    ]
