# Generated by Django 5.1.2 on 2025-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_delete_dliveryprice_remove_order_dlivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_delivery',
            field=models.BooleanField(default=False, verbose_name='توصيل مجاني؟'),
        ),
    ]
