# Generated by Django 5.1.5 on 2025-02-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_free_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='with_message',
        ),
    ]
