# Generated by Django 5.1.5 on 2025-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_orderitem_discount_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_share',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_price',
            field=models.IntegerField(default=0, verbose_name='السعر بعد الخصم'),
        ),
    ]
