# Generated by Django 5.1.5 on 2025-02-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_remove_orderitem_discount_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_value',
            field=models.IntegerField(default=0, verbose_name='قيمة المرجعات'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_price',
            field=models.IntegerField(default=0, verbose_name='الإجمالي بعد الخصم'),
        ),
    ]
