# Generated by Django 5.1.5 on 2025-02-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_order_reference_value_alter_orderitem_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(verbose_name='الإجمالي'),
        ),
    ]
