# Generated by Django 5.1.5 on 2025-02-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealingitem',
            name='new_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='السعر الجديد'),
        ),
        migrations.AddField(
            model_name='dealingitem',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='السعر القديم'),
        ),
    ]
