# Generated by Django 5.1.5 on 2025-02-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_dealingitem_new_price_dealingitem_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealingitem',
            name='new_price',
            field=models.IntegerField(default=0, verbose_name='السعر الجديد'),
        ),
        migrations.AlterField(
            model_name='dealingitem',
            name='old_price',
            field=models.IntegerField(default=0, verbose_name='السعر القديم'),
        ),
    ]
