# Generated by Django 5.1.5 on 2025-02-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_dealingitem_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='used_discount',
            field=models.IntegerField(default=0, verbose_name=' الخصم المفعل'),
        ),
    ]
