# Generated by Django 5.1.5 on 2025-02-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_order_used_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealingitem',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='الخصم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.IntegerField(default=0, verbose_name='الخصم الإجمالي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='used_discount',
            field=models.IntegerField(default=0, verbose_name='الخصم المستعمل'),
        ),
    ]
