# Generated by Django 5.1.5 on 2025-02-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_dealingitem_discount_alter_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='copon_value',
            field=models.IntegerField(default=0, verbose_name='الكوبون المستعمل'),
        ),
    ]
