# Generated by Django 5.1.5 on 2025-02-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_remove_order_discount_amount_order_copon_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reference_value',
        ),
        migrations.AlterField(
            model_name='order',
            name='copon_value',
            field=models.IntegerField(default=0, verbose_name='قيمة الكوبون'),
        ),
    ]
