# Generated by Django 5.1.5 on 2025-02-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_remove_order_reference_value_alter_order_copon_value'),
        ('store', '0066_alter_product_new_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dealingitem',
            unique_together={('order_dealing', 'old_item', 'new_item', 'old_qty', 'new_qty', 'discount')},
        ),
    ]
