# Generated by Django 5.1.5 on 2025-02-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_alter_dealingitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dealingitem',
            unique_together=set(),
        ),
    ]
