# Generated by Django 5.1.6 on 2025-03-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_order_city_order_neighborhood_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('confirmed', 'مؤكد'), ('replaced', 'مُستبدل')], default='confirmed', max_length=15, verbose_name='الحالة'),
        ),
    ]
