# Generated by Django 5.1.6 on 2025-03-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='سعر التوصيل'),
        ),
    ]
