# Generated by Django 5.1.6 on 2025-04-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم المستلم'),
        ),
    ]
