# Generated by Django 5.1.6 on 2025-04-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealingitem',
            name='points_difference',
            field=models.IntegerField(default=0, verbose_name='فرق النقاط'),
        ),
    ]
