# Generated by Django 5.1.6 on 2025-04-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_dealingitem_points_difference'),
        ('store', '0075_alter_adsslider_img_alter_brand_img_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dealingitem',
            unique_together={('order_dealing', 'old_item', 'new_item', 'old_qty', 'new_qty')},
        ),
        migrations.RemoveField(
            model_name='dealingitem',
            name='discount',
        ),
    ]
