# Generated by Django 5.1.6 on 2025-05-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_alter_dealingitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='max_replace_days',
            field=models.IntegerField(default=0, verbose_name='اقصى مدة استبدال'),
        ),
        migrations.AddField(
            model_name='order',
            name='max_return_days',
            field=models.IntegerField(default=0, verbose_name='اقصى مدة استرجاع'),
        ),
    ]
